### ISSUE TITLE
Error in magick_image_composite(image, composite_image, offset, gravity,  :    rsession: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/202

### ISSUE THREAD

**Issue by guanyuanm** [egeulgen/pathfindR#159]
error occur when using "Reactome" in run_pathfindR function, no error when using "KEGG";

**Comment by egeulgen** [comment]
Hey,

Since this is an issue related to `magick`, please open an issue on [the magick repo](https://github.com/ropensci/magick/issues)

This issue will happen for any other gene set resource other than KEGG, because the visualisation function for these require the package `magick`. 

You may disable these plots by setting `visualize_enriched_terms=FALSE` when running `run_pathfindR()`

Best,
-E

**Comment by guanyuanm** [comment]
great, it works, thanks!
