### ISSUE TITLE
Single gene in a significant pathway 

### ISSUE THREAD

**Issue by AliSaadatV** [egeulgen/pathfindR#178]
Dear Ege

Thanks for the great tool, it is indeed very interesting.
I used pathfindR on my data and the results of enrichment analysis is confusing for me. There are some pathways that are significantly enriched, but only a single gene belongs to those pathways. May I kindly ask if you can explain what could be the reason for such results?

ps: I'm attaching a plot generated by pathfindR. The pathways with single gene are indicated with the curly bracket.
Thank you in advance
Ali
<img width="796" alt="Picture 1" src="https://github.com/egeulgen/pathfindR/assets/89639213/88f217d6-c331-467d-a1a8-5f5b36e56b1f">

**Comment by egeulgen** [comment]
Hello Ali,Thanks for raising this. It seems to point to a bug in active subnetwork filtering. Could you share the input data frame as an RDS file so that I can investigate further?Best,-EOn 3 Oct 2023, at 10:06, Ali Saadat ***@***.***> wrote:﻿
Dear Ege
Thanks for the great tool, it is need very interesting.
I used pathfindR on my data and the results of enrichment analysis is confusing for me. There are some pathways that are significantly enriched, but only a single gene belongs to those pathways. May I kindly ask if you can explain what could be the reason of such result?
ps: I'm attaching a plot generated by pathfindR. The pathways with single gene are indicated with the curly bracket.
Thank you in advance
Ali

**Comment by AliSaadatV** [comment]
Thanks for the swift reply! 
I'm attaching the input data frame (please note that I'm using WGS data, so I assigned pvalue=0.01 to try the tool)

Here is the code I used:

`df_output <- pathfindR::run_pathfindR(df_input,
                                      min_gset_size = 5,
                                      max_gset_size = 200,
                                      adj_method = "fdr",
                                      gene_sets = "GO-BP",
                                      pin_name_path = "STRING")`

Best regards
Ali

[df_input.rds.zip](https://github.com/egeulgen/pathfindR/files/12791249/df_input.rds.zip)

**Comment by egeulgen** [comment]
Hello again. @AliSaadatV,

After further consideration, this turns out to be OK given pathfindR's active subnetwork search + enrichment approach. Those pathway's are probably coming from an active subnetwork where the single genes are in interaction with other input genes and the other genes that result in the enrichment are interactors (i.e. not input genes). You may see all the involved genes in these pathways by setting: `list_active_snw_genes = TRUE`

Hope this clears it up,
Best,
-E
