### ISSUE TITLE
Use Metascape to generate the GO term ,but not find any enriched terms in analysis

### ISSUE THREAD

**Issue by fuck7414** [egeulgen/pathfindR#195]
Great Maintainer 

I am currently utilizing "pathfindR" package for gene analysis in my research. 

Specifically, I have input approximately 4000 genes into the package for analysis. These genes have undergone prior analysis through "Metascape," resulting in the identification of numerous GO terms associated with them. 

I have encountered difficulties in executing the built-in scripts provided by the package. In an attempt to troubleshoot, I have modified certain parameters to mimic those used in Metascape, yet I have been unsuccessful in generating any enrichment plots.

I am reaching out to inquire whether I may have overlooked any steps or if there are alternative modifications. Any guidance or suggestions you could provide would be greatly appreciated.

Thank you for your attention to this matter, and I look forward to your prompt response.

Sincerely

code here
```




output_WB <- run_pathfindR(WB_agent,min_gset_size=3, p_val_threshold = 1
                           ,adj_method = "fdr"
                           ,enrichment_threshold = 0.01)
```

```

Result~~~~~~~~
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 4358
Number of genes in input after p-value filtering: 4358
Could not find any interactions for 191 (4.38%) genes in the PIN
Final number of genes in input: 4167
## Performing Active Subnetwork Search and Enrichment
`n_processes` is set to `iterations` because `iterations` < `n_processes`
Warning message:
Did not find any enriched terms! 
```

**Comment by egeulgen** [comment]
Do you mind sharing the input data frame as an RDS file? I can try and look into it.  You can email the RDS file at egeulgen[at]gmail.com, if you prefer not to share publicly. -EOn 17 Apr 2024, at 17:35, fuck7414 ***@***.***> wrote:﻿
Great Maintainer
I am currently utilizing "pathfindR" package for gene analysis in my research.
Specifically, I have input approximately 4000 genes into the package for analysis. These genes have undergone prior analysis through "Metascape," resulting in the identification of numerous GO terms associated with them.
I have encountered difficulties in executing the built-in scripts provided by the package. In an attempt to troubleshoot, I have modified certain parameters to mimic those used in Metascape, yet I have been unsuccessful in generating any enrichment plots.
I am reaching out to inquire whether I may have overlooked any steps or if there are alternative modifications. Any guidance or suggestions you could provide would be greatly appreciated.
Thank you for your attention to this matter, and I look forward to your prompt response.
Sincerely
code here




output_WB <- run_pathfindR(WB_agent,min_gset_size=3, p_val_threshold = 1
                           ,adj_method = "fdr"
                           ,enrichment_threshold = 0.01)


Result~~~~~~~~
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 4358
Number of genes in input after p-value filtering: 4358
Could not find any interactions for 191 (4.38%) genes in the PIN
Final number of genes in input: 4167
## Performing Active Subnetwork Search and Enrichment
`n_processes` is set to `iterations` because `iterations` < `n_processes`
Warning message:
Did not find any enriched terms!

**Comment by ozanozisik** [comment]
Hello,
There might be multiple reasons for getting no enrichment.
Setting p-value threshold to 1 is unusual, how many of the 4358 genes have p-values less than 0.5?
Have you tried enrichment analysis with other gene sets by setting the gene_sets parameter in run_pathfindR function (e.g. gene_sets="GO-All" or gene_sets="Reactome") ?
Have you tried increasing the enrichment_threshold to 0.05?

**Comment by fuck7414** [comment]
Hi，[egeulgen]
I've sent the RSD to you，thanks for your help
Hi，[ozanozisik]，thanks for your response
p-value threshold is 1 :  That is because I want to keep all the gene.
---I set all genes p value as 1, and set the threshold to keep all of them (4358 genes).
Setting the gene_sets parameter:  I've try different sets , but still not working,
I think the problem might be the p value problem, thanks for your advice

**Comment by fuck7414** [comment]
My problem is solved by Maintainer.
Modified below↓↓↓
Keep all genes'  p-values=0.05
ERROR->`p_val_threshold = 1`
Modified->`p_val_threshold = 0.05`
