### ISSUE TITLE
Directionality of Fold_Enrichment value

### ISSUE THREAD

**Issue by aleonti** [egeulgen/pathfindR#79]
When using `run_pathfindR`, is it possible to identify whether the gene set/pathway term is globally up or down regulated, i.e activated or repressed in the group of interest? I've performed pathway analysis using other tools (ex. the gage Bioconductor package), and they have provided mean change scores or a similar score denoting directionality (+/-) of the enrichment. I know that the agglomerated z-score for each sample & each term can be calculated using the `score_terms` function, but this is performed per sample, rather than per group (as in case vs. control). Is this mentioned in the docs somewhere, or is this something that `pathfindR` doesn't do? Or are all enriched terms identified by `pathfindR` upregulated/activated? Thank you!

**Comment by egeulgen** [comment]
Hey @aleonti,
Unfortunately, this is isn't something that pathfindR does. One can only say that the enriched terms identified by pathfindR are dysregulated. Since this (indicating directionality of the dyregulation) is related to different methodology, we cannot implement this within pathfindR soon but I have noted this as a future enhancement.

In the meanwhile, as you suggest, you may use `score_terms()` + `plot_scores()` to have an idea on the up-/down- regulation status of the enriched pathways.

Thank you,
-E

**Comment by aleonti** [comment]
The quick reply is much appreciated, thanks so much! pathfindR is a great package!
